---
env:
  global:
    - CC_TEST_REPORTER_ID=8a324aeb0d522d462ba8b6555875c90c15d31e299d2c251987e0bf31d9560f31
language: php
php:
  - '7.3'
before_script:
  - 'curl -L https://codeclimate.com/downloads/test-repo
  rter/test-reporter-latest-linux-amd64 > ./cc-test-reporter'
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - make install
script:
  - make lint test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
